export const WRITER_SUBSCRIBE = 'WRITER_SUBSCRIBE';
export const WRITER_UNSUBSCRIBE = 'WRITER_UNSUBSCRIBE';
export const INTENT = 'INTENT';
export const UPDATE_HEAD_TO = 'UPDATE_HEAD_TO';
export const FLUSH_CONSENSUS_ACTIONS = 'FLUSH_CONSENSUS_ACTIONS';
