export const USER_SUBSCRIBE = 'USER_SUBSCRIBE';
export const USER_UNSUBSCRIBE = 'USER_UNSUBSCRIBE';
export const ADD_FRAME_INTENT = 'ADD_FRAME_INTENT';
export const SET_FRAME_STATE = 'SET_FRAME_STATE';
export const FAST_FORWARD = 'FAST_FORWARD';
export const SET_HEAD = 'SET_HEAD';
export const COMPACT_HISTORY = 'COMPACT_HISTORY';
